version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.3
  build:
    commands:
      - php --version
      - echo $CODEBUILD_SRC_DIR 
artifacts:
  files: 
    - 'buildspec.yml'
  base-directory: codebuildfolder
